In [40]:
import pennylane as qml
from pennylane import numpy as np
# np.set_printoptions(formatter={'float': lambda x: "{0:0.2f}".format(x)})
# np.set_printoptions(formatter={'complex_kind': '{:.2f}'.format})
np.set_printoptions(precision=2)

In [52]:
X = np.array([[0, 1], [1, 0]])
Z = np.array([[1, 0], [0, -1]])
Y = np.array([[0, -1j], [1j, 0]])
I = np.array([[1,0],[0,1]])

print(X)
print(Y)
print(Z)
print(I)

[[0 1]
 [1 0]]
[[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]
[[ 1  0]
 [ 0 -1]]
[[1 0]
 [0 1]]


In [53]:
print(np.linalg.eig(X))
print(np.linalg.eig(Y))
print(np.linalg.eig(Z))
print(np.linalg.eig(I))

(array([ 1., -1.]), tensor([[ 0.71, -0.71],
        [ 0.71,  0.71]], requires_grad=True))
(array([ 1.+0.j, -1.+0.j]), tensor([[-0.  -0.71j,  0.71+0.j  ],
        [ 0.71+0.j  ,  0.  -0.71j]], requires_grad=True))
(array([ 1., -1.]), tensor([[1., 0.],
        [0., 1.]], requires_grad=True))
(array([1., 1.]), tensor([[1., 0.],
        [0., 1.]], requires_grad=True))


In [54]:
print(np.linalg.eig(np.kron(X, I))[1])
print(np.linalg.eig(np.kron(I, X))[1])
print(np.linalg.eig(np.kron(Y, I))[1])
print(np.linalg.eig(np.kron(I, Y))[1])
print(np.linalg.eig(np.kron(Z, I))[1])
print(np.linalg.eig(np.kron(I, Z))[1])

[[ 0.71  0.71  0.    0.  ]
 [ 0.    0.   -0.71 -0.71]
 [ 0.71 -0.71  0.    0.  ]
 [ 0.    0.   -0.71  0.71]]
[[ 0.71 -0.71  0.    0.  ]
 [ 0.71  0.71  0.    0.  ]
 [ 0.    0.    0.71 -0.71]
 [ 0.    0.    0.71  0.71]]
[[-0.  -0.71j  0.71+0.j    0.  +0.j    0.  +0.j  ]
 [ 0.  +0.j    0.  +0.j    0.  -0.71j  0.71+0.j  ]
 [ 0.71+0.j    0.  -0.71j  0.  +0.j    0.  +0.j  ]
 [ 0.  +0.j    0.  +0.j    0.71+0.j    0.  -0.71j]]
[[-0.  -0.71j  0.71+0.j    0.  +0.j    0.  +0.j  ]
 [ 0.71+0.j    0.  -0.71j  0.  +0.j    0.  +0.j  ]
 [ 0.  +0.j    0.  +0.j   -0.  -0.71j  0.71+0.j  ]
 [ 0.  +0.j    0.  +0.j    0.71+0.j    0.  -0.71j]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [55]:
print(np.linalg.eig(np.kron(X, Z))[1])
print(np.linalg.eig(np.kron(Z, X))[1])
print(np.linalg.eig(np.kron(X, Y))[1])
print(np.linalg.eig(np.kron(Y, X))[1])
print(np.linalg.eig(np.kron(Z, Y))[1])
print(np.linalg.eig(np.kron(Y, Z))[1])

[[ 0.71  0.71  0.    0.  ]
 [ 0.    0.   -0.71  0.71]
 [ 0.71 -0.71  0.    0.  ]
 [ 0.    0.    0.71  0.71]]
[[ 0.71 -0.71  0.    0.  ]
 [ 0.71  0.71  0.    0.  ]
 [ 0.    0.    0.71  0.71]
 [ 0.    0.   -0.71  0.71]]
[[-0.  -0.71j  0.71+0.j    0.  +0.j    0.  +0.j  ]
 [ 0.  +0.j    0.  +0.j    0.71+0.j    0.71+0.j  ]
 [ 0.  +0.j    0.  +0.j   -0.  -0.71j  0.  +0.71j]
 [ 0.71+0.j    0.  -0.71j  0.  +0.j    0.  +0.j  ]]
[[-0.  -0.71j  0.71+0.j    0.  +0.j    0.  +0.j  ]
 [ 0.  +0.j    0.  +0.j    0.71+0.j    0.71+0.j  ]
 [ 0.  +0.j    0.  +0.j    0.  +0.71j  0.  -0.71j]
 [ 0.71+0.j    0.  -0.71j  0.  +0.j    0.  +0.j  ]]
[[-0.  -0.71j  0.71+0.j    0.  +0.j    0.  +0.j  ]
 [ 0.71+0.j    0.  -0.71j  0.  +0.j    0.  +0.j  ]
 [ 0.  +0.j    0.  +0.j    0.  +0.71j  0.71+0.j  ]
 [ 0.  +0.j    0.  +0.j    0.71+0.j   -0.  +0.71j]]
[[-0.  -0.71j  0.71+0.j    0.  +0.j    0.  +0.j  ]
 [ 0.  +0.j    0.  +0.j   -0.  +0.71j  0.71+0.j  ]
 [ 0.71+0.j    0.  -0.71j  0.  +0.j    0.  +0.j  ]
 [ 0.  +0.j   

In [56]:
print(np.linalg.eig(np.kron(X, Z))[0])
print(np.linalg.eig(np.kron(Z, X))[0])
print(np.linalg.eig(np.kron(X, Y))[0])
print(np.linalg.eig(np.kron(Y, X))[0])
print(np.linalg.eig(np.kron(Z, Y))[0])
print(np.linalg.eig(np.kron(Y, Z))[0])

[ 1. -1.  1. -1.]
[ 1. -1.  1. -1.]
[ 1.+0.j -1.+0.j  1.+0.j -1.+0.j]
[ 1.+0.j -1.+0.j  1.+0.j -1.+0.j]
[ 1.+0.j -1.+0.j  1.+0.j -1.+0.j]
[ 1.+0.j -1.+0.j  1.+0.j -1.+0.j]


In [64]:
XI = np.kron(X, I)
IX = np.kron(I, X)

In [65]:
ZI = np.kron(Z, I)
IZ = np.kron(I, Z)


In [66]:
XI @ ZI - ZI @ XI

tensor([[ 0,  0, -2,  0],
        [ 0,  0,  0, -2],
        [ 2,  0,  0,  0],
        [ 0,  2,  0,  0]], requires_grad=True)

In [67]:
XI @ IZ - IZ @ XI

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], requires_grad=True)