In [6]:
import pennylane as qml
from pennylane import numpy as np
import matplotlib.pyplot as plt

In [63]:
Y = np.array([[0, -1j],[1j, 0]])
Y

tensor([[ 0.+0.j, -0.-1.j],
        [ 0.+1.j,  0.+0.j]], requires_grad=True)

In [64]:
X = np.array([[0, 1],[1, 0]])
X

tensor([[0, 1],
        [1, 0]], requires_grad=True)

In [65]:
Z = np.array([[1, 0],[0, -1]])
Z

tensor([[ 1,  0],
        [ 0, -1]], requires_grad=True)

In [66]:
I = np.array([[1, 0],[0, 1]])
I

tensor([[1, 0],
        [0, 1]], requires_grad=True)

In [67]:
first = np.kron(1.0*Y, X)

In [68]:
second = np.kron(0.5*Z, Y)

In [69]:
sys = first + second

In [70]:
np.set_printoptions(precision=2)

In [71]:
result = np.linalg.eig(sys)
result

(array([ 1.5+2.59e-17j, -1.5-2.59e-17j,  0.5+2.17e-17j, -0.5-2.17e-17j]),
 tensor([[ 4.28e-17-5.00e-01j, -5.00e-01-5.12e-17j, -1.68e-17-5.00e-01j,
           5.00e-01+0.00e+00j],
         [ 5.00e-01+0.00e+00j, -8.43e-18+5.00e-01j, -5.00e-01-7.90e-18j,
          -2.47e-17+5.00e-01j],
         [ 8.43e-18+5.00e-01j,  5.00e-01+0.00e+00j,  6.45e-18-5.00e-01j,
           5.00e-01+2.32e-17j],
         [ 5.00e-01-3.51e-18j, -4.92e-18+5.00e-01j,  5.00e-01+0.00e+00j,
           1.68e-17-5.00e-01j]], requires_grad=True))