# Demos: Lecture 1

In [1]:
import numpy as np

## Demo 1: superposition

In [2]:
def ket_0():
    return np.array([1, 0])

def ket_1():
    return np.array([0, 1])

In [3]:
def superposition(alpha, beta):
    # Create and return the superposition α|0> + β|1>
    return alpha * ket_0() + beta * ket_1()

In [4]:
superposition(1/np.sqrt(2), 1/np.sqrt(2))

array([0.70710678, 0.70710678])

## Demo 2: operations on qubits

In [5]:
def apply_U(U, state):
    # Apply U to the provided state
    return np.dot(U, state)

In [6]:
H = (1/np.sqrt(2)) * np.array([[1, 1], [1, -1]])
X = np.array([[0, 1], [1, 0]])
Z = np.array([[1, 0], [0, -1]])

In [7]:
apply_U(H, ket_0())

array([0.70710678, 0.70710678])

In [8]:
apply_U(H, apply_U(H, ket_0()))

array([1., 0.])

In [9]:
def apply_multiple_U(list_U, state):
    for U in list_U:
        state = apply_U(U, state)
    return state

In [10]:
apply_multiple_U([H, Z, X], ket_0())

array([-0.70710678,  0.70710678])

## Demo 3: measurement

In [11]:
def measure(state, shots=50):
    # Measure a qubit in the provided state #shots times
    alpha = state[0]
    beta = state[1]
    
    # Many ways to compute
    prob_0 = np.abs(alpha) ** 2
    prob_1 = beta * beta.conj()

    # Note here we will send only the real part of the probabilities to
    # random.choice; they are real anyways, but the data type they are stored
    # in is still complex because of how they were computed above.
    return np.random.choice([0, 1], size=shots, p=[prob_0.real, prob_1.real])

In [12]:
some_state = apply_multiple_U([H, Z, X], ket_0())

In [13]:
measure(some_state, shots=20)

array([0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1])

## Demo 4: structure of a quantum algorithm

In [ ]:
def quantum_algorithm():
    # Write a quantum algorithm that prepares the system in state 
    #               (1j/2)|0> + sqrt(3)/2 |1>
    # Applies H, then, X, H, X, H, Z
    # Takes 100 shots
    state = superposition(1j/2, np.sqrt(3)/2)
    state = apply_multiple_U([H, X, H, X, H, Z], state)
    return measure(state, shots=100)

In [ ]:
quantum_algorithm()