# Demos: Lecture 17

In [25]:
import pennylane as qml
from pennylane import numpy as np

In [26]:
def prepare_state():
    qml.RY(2 * np.pi/3, wires=0)
    
dev = qml.device("default.qubit", wires=1)

@qml.qnode(dev)
def circuit():
    prepare_state()
    return qml.state()

In [27]:
circuit()

tensor([0.5      +0.j, 0.8660254+0.j], requires_grad=True)

In [28]:
dev_mixed = qml.device("default.mixed", wires=1)

In [29]:
@qml.qnode(dev_mixed)
def circuit():
    prepare_state()
    return qml.state()

In [30]:
circuit()

array([[0.25     +0.j, 0.4330127+0.j],
       [0.4330127+0.j, 0.75     +0.j]])

In [31]:
@qml.qnode(dev_mixed)
def circuit():
    prepare_state()
    qml.BitFlip(0.02, wires=0)
    return qml.state()

In [32]:
circuit()

array([[0.26     +0.j, 0.4330127+0.j],
       [0.4330127+0.j, 0.74     +0.j]])

In [40]:
@qml.qnode(dev)
def circuit_single():
    prepare_state()
    # qml.RX(2 * np.pi/3, wires=0)
    return qml.state()

In [41]:
@qml.qnode(dev_mixed)
def circuit_mixed():
    prepare_state()
    # qml.RX(2 * np.pi/3, wires=0)
    return qml.state()

In [42]:
circuit_single()

tensor([0.5      +0.j, 0.8660254+0.j], requires_grad=True)

In [43]:
circuit_mixed()

array([[0.25     +0.j, 0.4330127+0.j],
       [0.4330127+0.j, 0.75     +0.j]])

In [47]:
U = qml.matrix(qml.RY(2 * np.pi/3, wires=0))
U

array([[ 0.5      +0.j, -0.8660254-0.j],
       [ 0.8660254+0.j,  0.5      +0.j]])

In [49]:
U @ [1,0]

array([0.5      +0.j, 0.8660254+0.j])

In [60]:
U @ np.outer([1,0],[1,0]) @ U.T

tensor([[0.25     +0.j, 0.4330127+0.j],
        [0.4330127+0.j, 0.75     +0.j]], requires_grad=True)

In [65]:
@qml.qnode(dev)
def circuit_single():
    prepare_state()
    return qml.expval(qml.PauliX(0))

In [66]:
@qml.qnode(dev_mixed)
def circuit_mixed():
    prepare_state()
    return qml.expval(qml.PauliX(0))

In [67]:
circuit_single()

tensor(0.8660254, requires_grad=True)

In [68]:
circuit_mixed()

array(0.8660254)

In [69]:
U = qml.matrix(qml.RY(2 * np.pi/3, wires=0))
U

array([[ 0.5      +0.j, -0.8660254-0.j],
       [ 0.8660254+0.j,  0.5      +0.j]])

In [79]:
(U @ [1,0]) @ qml.matrix(qml.PauliX(0)) @ (U @[1,0])

(0.8660254037844388+0j)

In [75]:
np.trace(qml.matrix(qml.PauliX(0)) @ (U @ np.outer([1,0],[1,0]) @ U.T))

(0.8660254037844388+0j)

In [80]:
p_plus = np.outer([1/np.sqrt(2), 1/np.sqrt(2)], [1/np.sqrt(2), 1/np.sqrt(2)])
p_plus

tensor([[0.5, 0.5],
        [0.5, 0.5]], requires_grad=True)

In [81]:
p_minus = np.outer([1/np.sqrt(2), -1/np.sqrt(2)], [1/np.sqrt(2), -1/np.sqrt(2)])
p_minus

tensor([[ 0.5, -0.5],
        [-0.5,  0.5]], requires_grad=True)

In [82]:
p_plus * 0.75 + p_minus*0.25

tensor([[0.5 , 0.25],
        [0.25, 0.5 ]], requires_grad=True)

In [122]:
np.trace(qml.matrix(qml.PauliZ(0)) @ [[3/8, -3/8], [-3/8, 5/8]])

-0.25

In [87]:
qml.matrix(qml.PauliX(0))

array([[0, 1],
       [1, 0]])

In [ ]:
[[3/8, -3/8], [-3/8, 5/8]]

In [120]:
U = np.random.random((2, 2))

In [121]:
U @ [[3/8, -3/8], [-3/8, 5/8]] @ U.T

tensor([[ 0.00476151, -0.011738  ],
        [-0.011738  ,  0.43662103]], requires_grad=True)

In [131]:
np.array([[0, 0.5305], [0.1768, -0.7071]]) @ \
np.array([[0, 0.5305], [0.1768, -0.7071]]).T

tensor([[ 0.28143025, -0.37511655],
        [-0.37511655,  0.53124865]], requires_grad=True)

In [132]:
np.array([[0.125, -0.125], [-0.125, 0.875]]) @ \
np.array([[0.125, -0.125], [-0.125, 0.875]]).T

tensor([[ 0.03125, -0.125  ],
        [-0.125  ,  0.78125]], requires_grad=True)

In [133]:
np.array([[0, 0.1768], [0.5303, -0.7071]]) @ \
np.array([[0, 0.1768], [0.5303, -0.7071]]).T

tensor([[ 0.03125824, -0.12501528],
        [-0.12501528,  0.7812085 ]], requires_grad=True)

In [135]:
np.linalg.eig(np.array([[0, 0.1768], [0.5303, -0.7071]]))

(array([ 0.11416214, -0.82126214]),
 tensor([[ 0.84008528, -0.21045684],
         [ 0.54245435,  0.97760315]], requires_grad=True))